apiVersion: v1
kind: Pod
metadata:
  name: testing
  namespace: jenkins-system
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: "jenkins/inbound-agent:4.10-3"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "256Mi"
        cpu: "100m"
  restartPolicy: "Never"
  imagePullSecrets:
    - name: evermos-docker
  nodeSelector:
    kubernetes.io/os: "linux"