name: Close Pull Request

#on:
#  schedule:
#  - cron: '43 6 * * *'
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull
      env:
        token: ${{ secrets.TOKEN }}
      uses: peter-evans/close-pull@v2
      with:
        comment: Auto-closing pull request
        delete-branch: true