name: Close Pull Request

on:
  schedule:
  - cron: '30 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "This PR will be closed after end of the day not merged"