name: Close Pull Request

#on:
#  schedule:
#  - cron: '12 6 * * *'
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull
      uses: peter-evans/close-pull@v2
      with:
        comment: Auto-closing pull request
        delete-branch: true